name: Lint Code

on:
  pull_request:
    paths:
      - '.github/workflows/.codelint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging
